// Comprehensive seed data for the placement management system

export const seedUsers = [
  {
    id: "student1",
    email: "student@example.com",
    name: "Raj Kumar",
    role: "student",
    department: "CSE",
    year: 4,
    phone: "9876543210",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "student2",
    email: "priya@example.com",
    name: "Priya Singh",
    role: "student",
    department: "IT",
    year: 4,
    phone: "9876543211",
    createdAt: new Date("2024-01-16"),
  },
  {
    id: "faculty1",
    email: "faculty@example.com",
    name: "Dr. Amit Sharma",
    role: "faculty",
    department: "CSE",
    phone: "9876543212",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "admin1",
    email: "admin@example.com",
    name: "Admin User",
    role: "admin",
    department: "All",
    phone: "9876543213",
    createdAt: new Date("2024-01-01"),
  },
]

export const seedStudents = [
  {
    id: "student1",
    name: "Raj Kumar",
    rollNo: "CSE001",
    department: "CSE",
    year: 4,
    cgpa: 8.5,
    email: "student@example.com",
    phone: "9876543210",
    resume: "/resumes/raj-kumar.pdf",
    skills: ["JavaScript", "React", "Node.js", "MongoDB", "Python"],
    projects: [
      {
        title: "E-commerce Platform",
        description: "Full-stack e-commerce application",
        link: "https://github.com/raj/ecommerce",
      },
    ],
    placementStatus: "placed",
    currentPackage: 15.5,
    placedCompany: "Google",
  },
  {
    id: "student2",
    name: "Priya Singh",
    rollNo: "IT001",
    department: "IT",
    year: 4,
    cgpa: 8.8,
    email: "priya@example.com",
    phone: "9876543211",
    resume: "/resumes/priya-singh.pdf",
    skills: ["Java", "Spring Boot", "SQL", "AWS", "Docker"],
    projects: [
      {
        title: "Cloud Management System",
        description: "AWS-based cloud management tool",
        link: "https://github.com/priya/cloud-mgmt",
      },
    ],
    placementStatus: "placed",
    currentPackage: 16.0,
    placedCompany: "Microsoft",
  },
]

export const seedDrives = [
  {
    id: "drive1",
    companyName: "Google",
    logo: "https://via.placeholder.com/100?text=Google",
    jobRole: "Software Engineer",
    package: 18.5,
    eligibility: { minCGPA: 7.5, departments: ["CSE", "IT", "ECE"] },
    lastDate: new Date("2024-12-15"),
    status: "active",
    description: "Join Google's engineering team",
    applicants: 245,
  },
  {
    id: "drive2",
    companyName: "Microsoft",
    logo: "https://via.placeholder.com/100?text=Microsoft",
    jobRole: "Cloud Engineer",
    package: 17.0,
    eligibility: { minCGPA: 7.0, departments: ["CSE", "IT", "ECE"] },
    lastDate: new Date("2024-12-20"),
    status: "active",
    description: "Build cloud solutions with Microsoft",
    applicants: 198,
  },
  {
    id: "drive3",
    companyName: "Amazon",
    logo: "https://via.placeholder.com/100?text=Amazon",
    jobRole: "Data Scientist",
    package: 16.5,
    eligibility: { minCGPA: 7.8, departments: ["CSE", "IT"] },
    lastDate: new Date("2024-12-25"),
    status: "upcoming",
    description: "Work on AI/ML projects at Amazon",
    applicants: 0,
  },
  {
    id: "drive4",
    companyName: "TCS",
    logo: "https://via.placeholder.com/100?text=TCS",
    jobRole: "Associate Engineer",
    package: 12.5,
    eligibility: { minCGPA: 6.5, departments: ["CSE", "IT", "ECE", "ME", "CE", "EE"] },
    lastDate: new Date("2024-11-30"),
    status: "completed",
    description: "Join TCS as Associate Engineer",
    applicants: 425,
  },
]

export const seedApplications = [
  {
    id: "app1",
    studentId: "student1",
    driveId: "drive1",
    status: "selected",
    appliedDate: new Date("2024-11-20"),
    interviewDate: new Date("2024-12-05"),
  },
  {
    id: "app2",
    studentId: "student2",
    driveId: "drive2",
    status: "selected",
    appliedDate: new Date("2024-11-21"),
    interviewDate: new Date("2024-12-06"),
  },
  {
    id: "app3",
    studentId: "student1",
    driveId: "drive4",
    status: "selected",
    appliedDate: new Date("2024-11-10"),
    interviewDate: new Date("2024-11-25"),
  },
]

export const seedPosts = [
  {
    id: "post1",
    authorId: "student1",
    title: "My Placement Journey",
    content: "Just got placed at Google! Here's my journey and tips for success...",
    images: [],
    likes: 124,
    comments: 18,
    category: "success-story",
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "post2",
    authorId: "student2",
    title: "Interview Tips",
    content: "Here are my top 5 tips for cracking technical interviews...",
    images: [],
    likes: 89,
    comments: 24,
    category: "interview-tips",
    createdAt: new Date("2024-11-18"),
  },
]

export const seedReviews = [
  {
    id: "review1",
    studentId: "student1",
    companyName: "Google",
    ratings: {
      interview: 4.5,
      workCulture: 4.8,
      salary: 4.9,
      growth: 4.7,
    },
    reviewText: "Great company with excellent work culture and growth opportunities",
    isVerified: true,
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "review2",
    studentId: "student2",
    companyName: "Microsoft",
    ratings: {
      interview: 4.2,
      workCulture: 4.6,
      salary: 4.7,
      growth: 4.5,
    },
    reviewText: "Excellent technical interview process and supportive team",
    isVerified: true,
    createdAt: new Date("2024-11-19"),
  },
]

export const seedNotifications = [
  {
    id: "notif1",
    recipientId: "student1",
    title: "New Placement Drive",
    message: "Google is conducting a placement drive for Software Engineers",
    type: "drive-announcement",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "notif2",
    recipientId: "student1",
    title: "Shortlist Update",
    message: "You have been shortlisted for the Microsoft interview",
    type: "shortlist-update",
    isRead: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
]
